apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: mqtt
spec: {}
status: {}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    log_type all
    listener 8883
    cafile /etc/mosquitto/cert/ca.crt
    certfile /etc/mosquitto/cert/server.crt
    keyfile /etc/mosquitto/cert/server.key
    tls_version tlsv1.2
    require_certificate true
    use_identity_as_username true

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-server-certificate
  namespace: mqtt
spec:
  encryptedData:
    ca.crt: AgAbPaTRi+o3CYL4qlG5tIJjsOrKJCvLeZRk/vpM860zwSi6Y1BuJa416DBRE+88DTZnZg/IJnZv79kC0yQf6jha7MPq4L25Wq6PNFNFOJ/N3Qy5YYk6V4fI0Rchp4OX4CXYocGtZ7pZTOf9m2hxgQVa60mjY56IGfALHNtxC/vPLyiv+wMzILsonx1qQ0VO3Pab11l+LL0uslAeABZzZXXHJOzJj7Kv4FFWEZrXG3gM0nY72V1pDXrvAHZ7zrSd6jP6vjWsCCpPnNXfrLkwThdEuzyI9JENAWmkKZ+8qA+W4NwMvhY/c4elfJZw4m268o+YD16hQcAflq8zPzoejga8Pyp2Xl0hijuqAxEpvm1ViTgDDMwNeqk9lARnXCxdbJQ8wtz9k7Yoyu9d6LT7efzPEx3Im+oNkr/FAX6ZFa8CYIJ7Ag4epTjlxjPllzjAOkoFm/4vlNR9ccnefdfSfky+U113cEwEuWLF0hgBbHXjpsHTmpHo2cwHuml/UDfhAEQ0dvhug/l7uQmw1prJEF7itk7HG+kGhiW8d5xvdBjjy7NaJL1yZrklQLs5hE6Oq8J/4LUIPIFAm7d/F2Y431AJF4MJSrXELwfO9opIapcjAdjBU6PHWC39KzZgyBjkPvnBWLw+97YZ/uvOXBNXCUsFl/qTuQlZfOr6kW2mAZ0S8FSLd5t2TCT3cTkQfJ0+bH3peUi9A01CQu+pEbYHipKn5pSIvSH9XGOFjj6XOrZtFMEWkrzt9CDUTmDf8BMW05dDTLK6wkNzMWch+OIROrdJNpwN2Dp1mc6hhaxCMp1Rz1kO9SdOWhD0bhyIp9omlfzWgsfNhjZVDFHEjU21dQdqmh4ZTFAbZl61v6A2P5QR+lWuDC1p/Qq1seXbWZ0SyKSQgtLznS9BhxQ7MFIF6Ma/A0cIs9xjO9JO9uJEAyncio5u3+3Df2jMpbP3VynnydGliPukr8nfLndmt8Ks0/AyeZRfM7NyuPOAgV6VgKGrryrsM34lk7AylQCcm+UiKenv0NMKBzI+bOe8G1ol2aSUMW3vugQXwFfD59ZEXachTrzGm8bLgtlVRXwOgYbzgOxIggdE9FIow+0WQpKyu+PgpKO4+ub5CFAqliuSWw4MBrlMbfV2CjEfMIiBYfEpMWrALY3okIGMJzOie6rZjcHG5/q4KonWucD0eKBflYbxlcnQf23uxbMLHPJcc09Gg2v7Ix+pMyhAL7jmgmhhGVkjVcyB72dlS7TPOLLGsYEsAUtUMuRvbYuePTt7x+wlq5hA3HrCpz08EV4a0wHCDakK4UvuzkH4NKDCtlVxDlMn+Wuu1cD4TgXsrCYj+6+Z4W/4wwm1goaMvsfIA0aEitoirjA/kddoV7a8vkEQwSOSxpuRm2DeTdLyzpHg9mGBmDsca7DLP2tTx2WHHsJ/ySrypCdwmUL/YCn2Wk/I579bLBX1r9Rbql5jfXZGWpELLSY8DL7gGe94Vr3omTgdAo0BSRp9djMT6fYhS48agpkr3WPFCS+abZPzResVd/4Mvz82McenY99FMjWJmSPmXnhkhJiNagmJnfQbNW27hr42wLk83f0EuEcfFYAY0V9mLSJwOUlQ5U1pjFWg3uP+qnsGOPAZ0CsT/nlev4q7wmBuJmTxFc+z0XpbGKx3Kw4ZD5TNAcqog6jZ1cZj+hmCKt71ie2ndnviumSMRwQg+zZZ1cQ+iFlgy62MeMB/yovwqk3WrG3nvQ7aykyDnGRye+c4kCHPRiEgEsZC8NS6mM3hdZmfCy5I9hgfI4BEDi/zUqy/heElv3tggEiKxlu3Is6zDrfexIqzOkl/ZFfFG8bx5iZ1sveY4GIuOuDAxRA/ye3AHPnrSR2T0whdh8Oi3T3TJar++NXoekY95wpY26RkqcUev9qDpxw5B9AHaxLcYfXZi3OtmAsN8AagIpJCZRw2vx7nFpkvhhdIXb9rjUp1vJe8g1X2tKIezoM3FaHFKItudEtQ6tQ5j17bPEwWSZT5/plRiVTY3GXZrrmgIMcYJgm14UQjOZr4nxAzUTIbuPi2ODjg6HzvsHXUDg5WH+ZnU2H32pakzp5rzXyizrSDVa/KgdxLY3UbqmtMIWXG8OLLXj5Q+MuK1itMdaWqWcn+YTazIawZJw64b1e8BwBGtBVMXEDeIOvLjk7hZ1SLnbXe8ZfaSyweiaqMFWcFXagM6jAtcCaUdAi7Jgl9I61B7T4QtxM/BIXH50otwjhKVN6IOAnVEsFlyzUGcil/Aj4UHNbSsMV4kuRv4CNEBsANgBT7Sp4=
    server.crt: AgA7ODYuOxafElwKNEMOPYMhrD+6LqAGYmUmOTK2R6oSnfiHj9EKUn3Wax5JjJnL1EhI1KVy52wU2XBAVfLT2kvDZZpKn5h0BqFyicx4nxbYiX0v3YlbLUCajkdUOBx1/ZJRJGQ43vFuKYzJRu4cjpf4tYu+sisXLLIOlqmAuu0Sps1fDTfisj2fKuSFkk3ob5SaJyEStHSH8hhFM6Vj5FuD5RyB4365/eygwJrvRvFcyLNmGhFoUpCSbTv5g0g3QOnmJyZt+a9ouJu/pCphvTeyMfYLFEMYC6YXuF3ZFL6LjlgFGYw8yF50sm5zO4sNr3OSI9/pAzWDF9kZ9mu3xfmrn1ipFhbRt/M7G9rFc0+xBG7yz2ruHHDTOz+RRmk2spZh2Wn827DSCuHM3JpgJ+BzLQ0IFXTImJYh2cwSSoPug7/jNcnHHBJo3c6iHaNAkxPSuVeJ0USJwyD2oPUcjJDEPsPYcaFL0El1l7yp5SAUCAizaa6WLsPFRj9KbS5WhorepQxzbkf30MbyY9HETiXpCLC4b/3fJFpCfuUNtaKsLwDXf6E2cCmsKbY4HD1ICzQk1XXDPdn5lnnDxeJbK5fjr2DwL0FlzbFPMyTF9mnXW8Xa1a+3vLaSPRJaiqY3UOKk+Bkwxs+lI9+9IdyM5Q1AR+tu7OmOKg3nrjYuP0TaWIDqSHf72lB5ia4dn8+c2Iuhu+AkrzzKtgQ8yOtoPMTcfBtK/NgCbYjv4MXkskLzYVNyQ0IC4SmJRDCfgK/w8jLIqRCsxnV2UpatTBdCwN1SL2mQ8/oe/bYmg1ygzxmV9ZvgOtP7M4QoyZq8SQp1ceaP7vnihXFiSDMYo2kqU9lbSUYDcuLHOvvJUBG2NXEYwZd2GK3D38+CHJ00COUlWKdqlh+Zp4LOWVZeHsJKRwn6uWOauBx+kOoAaWJhd8p6oRCJu93+fogTaxdKjvIQA2/giE7mZ3k18YLogMRbNQ3FqdLegK5sJkP/1crxUvFkslHYS3lT+y0KEqj9SJZFwws7GZPbiJn1wPYgWi5JxI0CrwWwmjKkYs5itrGIHNCq7Vm+2SJ6FNLY5ET8VKbedlx9Cp3uhTsMl2p8Ptfjyv/7Jb+8XScw/1szpKzvSsgi8tXiCnzHgPN/w8sWmz8O9WoD/C9aB4HqARFwZ6Gd8R2xCmXz+AAFGk5p+gom/8N1XZNMDZG6+J2lu1LEKA5epa/12wEXDxuCARinDOK3fz6K0MMLwBcx2Mn2rEfB8wqPmWJQaUA8/kMj6aX7ngsB3eTHRcTuihQjk0WaJB8ijRIBTOxl39m4NUiVNMU9XyvyiTyFBxbwruo0cEZLmIQ37Da6Bnstib14uAwjT99STnD9cbQvRhqm5iBakiE/GyOrlyE0N8hBRkq/cGHrSwYixolNDg9WV6qY1HJq9B/K3xZNBEdLLzU8t3dHxn6cIa0/CbngtprGoqRqBpRGtGHYhDhJSZZbQXOHPh5O9lOoyv6g+1I0BS37FSzv12jqVapaw7Pl6ZBt9z2EDmtfBlHBTje2RN09WjB0eS9tOirOWizzvr5PHXXltL1r8dT+cgyvw4fGaNw7xfJvCpEu9zuExv3VC3J1yLnZacDGt54eVWI1zD2OvDb1b4HGEdMZEZ73pmoE1mEJnNbH7mgAaYEEP0uTddrsRJmdpDM+8AfIALV7BLd3ayKqPu2cRafL9M2YwQ+C+rk27uafD1gocdo4tZOiAoCnTK2+rXEXqw+GhpnLXnf8gvUx3/V5kWuCm/RRabeF4tD0CgQFGHqJ1QPhwFEslj1T3h0+FHL5epfs/PAgtU3BjuHHj/bG54HhUmdxwNBtHRxiHLkLZmv4zdVvP6HG26PtBa6FzM4yULRz8vTX9ESM0qOiTcO6SaYDb9ooFhjikfv5gNIqiuB/XvCvtdAGGN2LQJi68MmD40jmR8SEMOgHmER2gGZ0NfT54ldUlwHvInew723ib1gQ2dYQC3ZToT96IGX04yf+0zF3fu3+jZ6oQJqP7kRmScAYKKPbPgUC/9Ma6aAoC4kfSbepwviDdNrlTjzMKDPwv07jEVFTzYHf4fpRvAC6eMTGWwmWbOePLIVeuXak5ky1YbpTEV8RAM7KREbYavBBtyDlsXByq+c13pEQ5Gr8xDNCq8s3fu1MbVH15xjwJmild9F/d+3F3zs0lgnouovJLQJ3dilLoqY43WNz0+DUX6EVmWIr
    server.key: AgA5X33qJLgC80Kiuv9+qYDF16Pnd1d1VKFjEktVbn07e9zAMJ10t7pnc1nOcWtlfPLPScfhlMmo0HjzGLua+z2Zn/JTPfEON6ckWvEHMg5v3ktHdOEywugje+/NzWZ5RbP1JQ0Z+jKJWlKPsvVgGpNJv+Qth6qAe2SYPjplKjYwsbZu88suejBn4/tpLLZr7jEcsZ/biQnaPbKjMz3AVOrAqKqfWUkTdQSCZG3AODp6/l/ZEwBel2qHORcNjI9LI9nkHi/zZzy5GSedmEhBxfWRMklqxviIXcYgs0SgiTCitjhNJJduLfvMHKMXJqJlghmdQL9g8iqo0+gpC6CcAB4QMuZlazdwjxx7DUT3UKuplKDURx4wEpfaeK8XFYoLIDrf3t1EemFtQp7Hdj2AlYjfsWAAv9VSijvP7hFE7OcC1EBWiEEfuvGddrv9FMdL6SRK8DhhTx+plvBSpl8702tHRB2Iw/rnKIA+7xM8z7JNMDicGVGEpv50rWEBMO02cDiYMLWi0fNnUuvSdLQdWVTStfMOB8OkfnirKqQKJ1SxuUIIZ9ykVDsYDcK9RZ+3zaL0vZ3NfBnL8ffB+pV8jiPaH4Jg8gCtR7jHzpguUlnQyaNl1ijBxD0LTa1Ihnwst6+3umwu6GOk+Hfaz4DBoA9vzlb1zsxmjMP+pKnuqzQ0DcU4mZtWiNSZia9UwDf453SSkP/QZw0HWXH1k9XP8kvmvLh4KO7fCRnnMINMAE43fYnNYkuRL2/6o8R9X1IenaljeCo9D5Fu0tHC8G68nKF0ll/i4vOFWMDcMbCsgPSgCg/A12u5A7GaWs/tP6F9i8u727KZi2i14Q0D10rPdn81EiOBWMbb5eew+yuyStbkHRCsfPgNuZvrOXQ9vgNbOfSwcvC2VWiS5ScJC63MNluoEOTKVCgXzcBt+QfQ/pSu/KL5/psxNm8KAhO6sc+L08ZBZ5QvME3b8Cin5uOrAi31YvLZHvA3LPwEOQxmq0JeiDQ3O8BNbQsXOhKRcnqYGUmQklJl1si/MALNJKW28Y8h9rVyrptn60SXVgDpYQSv+x31I2sK0EHhdSlenZCfHqKl2Ymzy+O2X3t2u7epeRHjjll5Ks2ofrNumzgYSnJ9mlXFKZkA4FG5SMK+4aR8dt5ycWTkVl+uRyNJvrYo7ZTI0um6Dv2nTnDW/YuI255IZ49LF/O3wablEzRqXy4b12gcfACwV5VAg0ykLiyQG50foai2Y+Y6vlY4wKciJtnGQh4ICC23fbL47EnFDBBPDVpfMvK1QPy0J3SwRQjhc7ptaL3XyQ2aZ1suBxTCwKTshe9gY3TZ3gjcHe/eNI8VYtaCsTJV+hUM/+btylFT5h90SXNu+POIPgTceJ4027szxlPYtnXdmnZIqkxw4f8QACWkBLV7iBhabKQy1HqPlpp9OLx9nhS/NGAhISmfTqfV1L861ljiivdZUvp96fBTOi3FfhQ4SKzBsZtJxXV4msiIuMxnl/obxofxkQDvKG8+XvQfIxkkKTWlHpBKJzf/XU5S/fzd/ffjODGsJxgR7w7Y3ztsz7KYrTfQK+b4bZVqGmqv8YzCeLtA8r1TtJhKXErphD/5d6ubybeMlHiEFUJEDcLDI5t2qlwwMORC0NnaXuBIIot4+VgH5UHFX6CbDIK86k6VbDEEDC6UHfb76qzmmiJdzRc5yreTdmItcFZYNiA3skCkCL+/XWHfz3QRqEnzP+6KLb74sz+isuSx+XAWFbbifrCHPG0jB7OSa5UMxhFp+EgyyyG/ffCzOHQHyLdaMcU4AHFGIeRx7piuKMNLNUfw/xLLq9On0RRAB6baGerxh4aRF4cmPu1hZn+1xeBP8JVR/NfgQV/atQ5uHOnbyZIdT7ZuuD5mwNvzjPiofuWc39lVv5JOdPZ06X+WaBgDHUKGEFJ5S7HJt/hgFQruIwScuTFADK3A2uySQtvMLHJH2aU7Fcc/XftEMwar8Zhw3KBS3Z3u3KDYTdL+YuFoo/uZ+jgv4EuoAYVNzYUO3zdrNFmja8gXeJ/8jsFhloPckdyTKk5MaUAK0XdAnQgGs2Fa4xBnK7HhXTKVa2MyzyN2lwng07RDFB2ju3kknR7PDg/2bOzL0LHWckG/LTsA1Xv8CE4fLw6CxNgbrHhcyyhBrBP+4sQqTGk+megdiTvW15tGWpyAtAhA/cZ/YYZiR3vv/7vZb7a9HCRlGBEtt8YXLJ6nSxaxe/I29mS+EPvlno94KjKaIsj6PAXmasANmdXkq6yhNwHlrkemjHHnG6KtToLpr/McjHlN9mdlDsKddCpEEQVDemII8JUjbu/vP/RA0Bwzr2jEiJQItc7KQWsUANPXXKpOqmYCwi2oGvCAWwkRjphWmfNuxHB4513ZLghOGOVm71hfCq++WVWpr4kIN/7hJpXpJtujFazlVn6sG8B/BVku2RpwFpPXhq6VPeIUatZrr3wiKVDFBNJLh+CNrvbX9PeDzAXoj78lWULKbgOAvN9C8EGL4SINVbyjxEesVoAqm8mDQXNfJ3nF2TJ3da3n3NBBJAPSfSf0i9A//ldaxtsSOg0BbwIG98gDQT3oXlHiqAwJuhhdR98rwCXT9IXJSl785dDv5VVuoc6q2t07kUBWLft7XXGchF+tHK53JBMDa3Vn0ZC3BqnmN7cBvjthnWSPCvki3sij0s+vHitgz05d8V+qvl+DqlqDX+J+5PrzHl6yOhFBq2YA7dJ+OcQJxUHBlnA7Y3EKO7zV2JkSXbm43x6+iRCgZdvihUZa92A3DPnGYoEtlWRhrehfJXNG8cEjLPv23Va3RmPNjP7kye65yvq6LfxrOW/qRvKvPI6nkI8bhxTyIwYsaRVqPW4sRokSZWFXplMqHhdjIP8ioLFSie/ugG7QAtIjARlUybTkHh+L7yHg9r+YvlfLcGJ/iTcupzRy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mqtt-server-certificate
      namespace: mqtt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mqtt-broker
  name: mqtt-broker
  namespace: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
        - image: eclipse-mosquitto:2.0
          name: eclipse-mosquitto
          ports:
            - containerPort: 8883
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mosquitto-cfg
              readOnly: true
            - mountPath: /etc/mosquitto/cert
              name: mqtt-server-certificate
              readOnly: true
      volumes:
        - name: mosquitto-cfg
          configMap:
            name: mosquitto-config
            items:
              - key: mosquitto.conf
                path: mosquitto.conf
        - name: mqtt-server-certificate
          secret:
            secretName: mqtt-server-certificate

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mqtt-broker
  name: mqtt-broker
  namespace: mqtt
spec:
  ports:
    - nodePort: 31883
      port: 8883
      protocol: TCP
      targetPort: 8883
  selector:
    app: mqtt-broker
  type: NodePort
status:
  loadBalancer: {}
