apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: mqtt
spec: {}
status: {}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    log_type all
    listener 8883
    cafile /etc/mosquitto/cert/ca.crt
    certfile /etc/mosquitto/cert/server.crt
    keyfile /etc/mosquitto/cert/server.key
    tls_version tlsv1.2
    require_certificate true
    use_identity_as_username true

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-server-certificate
  namespace: mqtt
spec:
  encryptedData:
    ca.crt: AgCT5VnS/tCR4h291bDpRNkV+zDa/8W9DLvB5aD91BSN4aqi9NWKy5kyHt+KoWEqiN5fX4xPLAxfnMrX077QRweT7lIdGZjGC1dROls+nZJpcVPoJ98iJHl9f8VpyuUipKFo9lPtH04Wn2CuBe4DncXAJT9xBaSWPW03Q+MXkfQShyQMEs8wkoOBS9mjcL/dj5W13qZpnI++MVNyeBQqZwQ4tOXh3lhPEWbLQULAp5awANzEbUkbZcR07mAlwQOzm8HFu9X4gTqanIHew4IvHA6EGnEKLXGdraXA7FMvRF8fqX4v9O71ZNEe0LgRZbapmNt/5MDMULQPjrNHHxhM8lAHDLDqO2TuHR5sXe08Z09K/ulF4PkPwWBJvgrla8Gw0tbm1SB2oNwGunX1RXbiLSKvWq9qCBpo88tKHMLGdv+QwgMXghQlk/ghqEYuHSAvmZjHx1FiO9irIetPkXaqOOPaaMJFPzRH4dI9gBfmVL8ZXTy0shnW9TnUQPTppi156IPawZ9LZSel6WKKeCq+EyRuQGYTsEtsJ/+nyIAq5WPSL2ryzpVjb24P+oycCFzqyr3zY+BmKxpEGTishni1nVFsJI43xGednlDHSKc/xQC3+0KGWYLO7WwvXxqnHgQANenuTXIzX0pHVfsB2WupCPHhdKASt2o8fzz3g40BUgd7OeP7ua4V2ophMj4DLboyxC/BLedZTHJM58GOvkfvYNd6BGAxa65wOftcp5ftKE5ZuXtV9dRv0JVdL0CpXJZEzCVFRM3ILXdiHWc6EfnpvjDDsPwMK0NYTZWBZx4BcaaUmYys4DdcDpw2ea9qMQC2xOrQ5z2v9YQs88Gu85VSPFBcfDAKFoPKvQd/hhuxqfnmMUlqsgOYfr4zfwSvsOpa9kAIf0MY+07v29Bmb02ZtuEooMP2OBN7K1ja5Khx/UgRvhRBotGmWS3omsb9iBBZZXKwdcKfzahGLeJZh1Rw8Rhd1RCNr4z8jrwu5X7oZo6kphMhqHjxCZ+qzUR1jDZS0KTrdJ26UR5S6glMwpd8XnMFTy8L6vfwD6lJ1KV3p87B3H+B2NpAZhysM2CxEieeG6jMWa9eGPIE/LFnPVq/FhBWq2Bw5XSiHJXj9+fLIABK5711mDF7mIODxEs0xfhX9HL8Q0CdWwvTh4mYUhPlMuZASl3XrkRfmD9xw1dmf7sap7MEfP1E/6eH0O2jEikj7iyL0SdjuDk6mkZ6Fh1svPZe/dAqOC04cM4o/bx9y7KtlHdrkiO1ZCD2WHq3PJ4GZ98VxhocpoMI1ZvuJ4sdgGOXd+REuf+NawsNUKxGEhFgJmWZRvvOgLhVI7i5j61/f756837atDgR+PwGoNyL/zJ/DD/7bB3h0Q1fRZ9OyJvDKFJiuXLjcPpavIZVXraHJxKzgmae8sN+nHpjdcVYu0nCebi3UPqKh2+uQYLNLa2lbncS5ndnwADVfQGnhMS9VyXkDFo/PvJb2+D5uXW5ED/QM3WqMM3DS1GvnA1Gp/nFSNBFLGNy7rsVFuVhMoYyD5IU0vok9PKwiKIp+bRPWi2n2Ik2ByEL2K5vhMaBe6E5LnpK3mitRvFBg/tT4a3cBhKUESbo0DXaP9kW9vjkNJMfkZi0UmpLpyJoYeDXjyAITW5FPIr0YFaG9Jd/Oc62HH2VSoMxwAKxQ4+BYs/eq9Le6esQWsIsCpx6NCghvTb+/HQzpxvQISPPdfbiLZtM3O9TTIaYaXB9wQovk5Fm3dIea5LYEbyYCT20/JIco44ELXYz4BPgCSee8nNmJcyd/px98HNzSVazG6CtDcx+QTgxfPVzcIGNZ8hpQlBNpLWbbLD0O1aJA8SHrNnoZWu6ZcvbvfFzkd4ML/stUtaQUDVsZGmwJLBdCm1EAAnS3wE8/odnXCxxSVpKvHxMywlBIlwd//bbOSbpTC69Ixc68es/ae3sf/Gz7oOgvERH+Evy26qmoZNAArAE1bA7H/9IVFvLqZTYRn4auz3wPh36M76rkN+HD2GgX6WUQViYIzsdIr+uADrzRd2o9YBIL8R9I/Jtn6+69lxYKCx+ztCmlNR4NSdOi+JFHreZl1p3+x7rLlOv0YWZuy/lkqqz/z9ZVPyF0g67/TdtC3W1jNz7PN1I2dHtre8pw5prDFKKzp7BIucNPSTXQfFu4lraAbCkcrdReTm/2xaAKxMFZIO5kp2DT+LQ1aNG92ajuAojZ/SYegAzZzvr3TZ1j1LMxCz+mPn5k28hZPcjgfnFabFC3unU12xakD1ap9Kuom3qCKBWE/z1MdU4d90Dx2N523wQLTso+mCsgKhqmA==
    server.crt: AgB16w7ccFTw1OBPf3tmpIOGSvjZuGbw8CJ3jC/T01Dj+PLsFd8cun8vYMo6dfwdPryPwWDLe/uNC91OkMp8dx/i/y+yZGLKub1Sf4J2dxIK4anx9VJReLLMzudS513Qew7I0oLJ3NS86uvt8mwAtBowFD/A7s0PSDoaYYAipYpedLNyn9UrByBpIT9xfNHNZnhWVFVhbJWmJQ9ijv+9JsFm6IYhZyV8VMFpQ6yfwge5873hGpYG4j9C8tCgHCOvRwBdrzNWqLP98H9UorIdYvvssEJDGv50IkZr9iDQl2GfeWxMU7ta9N+LdKSMB5btYxwZRj8rfGnHFhHRwUUAk8DqhwyWdqpJzLeGdtjnghL+NA5QWzIcaHTN+iWapshkOxXXzZ99/O2SPa3eY+HLQ++QCxE5cAVosAsZIVc9U+5Uh7jYDR3rZ9U84RJqzSyELnWI7zt1oM/AQYm06pJQR9JzdsL4OZGXMavM91D661kqKxbfHnG9V3AfzMZ6PJu3CqU3RqRA5ljtUw5ohvVd+nZ+WFJEEkMRXgVssviqu20DzyAjfVwbSEbPvORqAF+r6zIm0zwinjn54qTV54X05S8yiYlDOMz6gK3mxXjXgUYrQp00a4CM8ZODInGmgHZ+bK6JkWoPiXhEjdWuMKUpXeNwGIEr/giXiF21I9bC+C5+En5k+gtIJ/yubLdbEpAAFJQkiEnrrOkkizQ8JL2R+04m47AinzU/SlXbEGdLNOf2OoMXP8MmqgG7qY/IT62Godtp6qRioguD1lA+IGUVdGnChEj95dA221PKssynth2Z+I0lb6hLoxaLcWcA+64MOz3c6UL4IydmF5k2l0M3a/SSqi7rurzDojcA3R3VgjUZMJHjbquhtsta+rEVFR9vEDno4mvT6fhj5EfxnTiM/deTW+50UXRsNDd7Eeqhc3k4BSf7LLKYJ/hHdjGVHJ1zoxPoFGliFmenJEwg+CrZBwO+t8YoEZR5vkBY6gAOCm4N8byJxCseSO5t3suWyO6OGvrho/00m3PeA+u51WCa8JEV7wJlZ3REdqQ4qXk2AprEaILmi43mDLkP27iR4Z5ZNmKXAeuyAiNX7GnRc4OReStAVE+j4lUJL2nzVA/KB9qez0b8GfU/VeMJoSsJEOs3zNUZHlAn2ZfcwXv0UPc5L2bUFMXxXmP839D7W2Jlu1eC4vRJ6gJe1NTYHfjHwwEHRtb/rVt8yDr/Rk3LTrj3j2Cn/V0TXumCBef8ujigFk7xuJmo43ZoWYzsaH0DqPjo6fnm3BStovporrBoiIKKSV/kP5paELf625M89KK3MvPdWksNTiT/adDNYGTPUbXyxjpWPq8eFf/CJsFIxgDYTM2tY8AtCVmUhiDWDggKldqD4IMHi1oBoEJVB1uXXkj3dOq7Pr++HgI6iEJKcgTky31xRIUI8ZhpSu2lZ8NtG4C4YyvlAJBvwPOXBEhCEi24qmVPfmLHSmvTuVfxI5QTB9Riz/vNA/rCL1UoUTayxdVb29jY94YkVH58t5lp+B1QtaozSEvKpD8YlnKYamvqaVN/e9KG2DZ6xiKBIfXPNZQvy4vZBpQzu/FSE88Iv3R/BI3gnJbmL5oody+LxMFcVxDqbXJIAnWnrhZvzhD1E1lbxJ2FwMJaQe1xJpQaejsR6aelx4mUoMVB3AsUBdIbSU4EnEfY8Qsbo4flwJjWfU8sX/TxWebbcud3bJe0R1M+2m6ufhDwVxloJXivqoT1bmRxUN1dVbwe2mqqgRyqNduNUYD5RyHVbR7WfrNakwVSJn0Rfajam5GIFiCOuYmFdvblVLxnaJhDZQbDftl/YktnXc9JwSqzNmq6R6tUmZj4GsIeJxzKzd7Ut5Pcx1h0sCTlCH7fYkpWlrVFhwl8DAnz9fIwz3cpNTh8KtKDGjp9wZ7ftpuJDRlG/tkP5qs/O7cN4kxEq9+xzxvDC9YBjy0SUkPX5woJ5vcCaoJc0MWEzHQEWWZOs1JXcsKTo4tqajfKDPHZIIgDb0qXVPAQznuEzq5zsFzi083tcD7KRlpoMsWk3LcEew2RoUlf7pbM9FeU4Dg7kNh50qBkcjDrRX9lPjzpEp6B/YOwUM5CG9pbXYL/ZImFh9nyt6ri82E2gKnYmcI9JyQ5L+MJnqmWJub/DYsQ
    server.key: AgA3WHx+7nTyQigSFroGjEu2YWtNit6zqnRVTl6YKcMiX76bUXw+8ZcBdUxaQNauGFgsSjjeCQHsRI+m1as/+odNg15kLHxCW78HeFsxWFZrEaWIRnGlsF7ZuvpPfwQZqYjFtmrDzR/i5u00souDM+2rr5AugbyLDaPPLG8Z7wVzKucAOVR996XKacarYlENEzh0CtUTwrvdNzAwd9ubpHEpoEjiMHZtpd7DBP+WTb6TOJjvMHv6Id+kLHs30eY8nnX07R8PIsJY/oYOSPS7Hzun3XWrCS7IHk0kGVe+GdrU+1v7LJ2ORYduX37/iO4rb0qCSstW4JVligg0JGxx2UKEKjl10g46Yewb3vv4+qOqkNbunGuqTmWtI/pA9watk3nmAOq6GwRq7EV2SxqRsV/8Suh9qW+NMp/D4Jcf/IuiYoyvXg97FvPiVJgFxW6on7Ax5jVGZibS4xGeoEdoForH58BE9FlA5W5JeSGHdZErhi8nIjU2UGEVtcpT5d8ew74BPE5OLjuSGxUiNw+t3+y5s7syUACYcSiL3tm/gzKLRkGfmUhFrMa7w/etVRj0b3ssELlag/Hs+2vaDGygXMNgcaArlmkiL8fzQ/FajqUOnEVREJuE1+e/7i9B7onBTyFHW7tLFM1FJxqdqdedgWosWWHqm2F64+uLM4+BLqzrebu1WTGlrP0e8Z6YqI/ZGWq8rsk3eXFknN4eBs9z0ZlDJ/08/wsR0CiU84hZgWoMhELV3fb9kuQpJ8T8qOuiy0hI/fSfu5fzsruNRDo3x59gYBHt7q8IN6HjxOep88vB+nMB5Jq8SU7QIA947JwLoU0m2r0X0Lf1+bdLE5jIQV0JwJ1T1uipkfLnEYIYHBxaWaoe/NpV+XiKyWiFenXTCtMC2TZ+yRl4XYx3R3yizirbyTB9n0e7+vDxoVoiN5vvk31wsmV/gpWLeOm41ComATXxuwD5OicD7Pr4vYbpg+qVjtWUpH6hYXDENdq7eX8lNNpfJfOMUh2tZOyVSE/KFbcOKzy1FR2W1JfTtLtZMdh38csnTiImxN159X7LSgP5uDf3EFQt8imYYSH5xfGo0U9nMdXio8MgAFZ+/ks/SzdsK8syj+aE9HSuDloL97aBD4tAMdweDwMyUTo6HklvWI4ThotzIykMTXGUoJjAeB1InQh2QYktJaz5RbjC9GLgIA699Auadr8X3DONkNc+gJufkrMg0D/Z6IT7W38sZBcz3B+Wfri6e/fBDJj9IiMfAdTp4x3rAw8Ds6wRsbzXCSvWGxp2mk9sB7h4E9sr/99fxqptg16NfBwZc2gr314Xd1khRgkLjtZF9454VVIPMc+x3cWKkXpMiPWwDm3qZWobZiwX8gKuoM/cyo5HCherfccSaNfBEizOElOXkJ0cfFra4IvOitSwWqWby6hYcXYjpVHeXjl5ZxGj3sptSxQqTAUP5jNGwDo0SBFY4u5LdZP1oEkLRAkRrZ8egKBRqk80mBv5bRpmprsteX6Y3l17LBlGA7wXOKl4/IRlqFvu1GuGJykipVzQhlNZN2zYSmXpuP2AJh/UTo4fbl9QOyZBd3Z3d153OGHsWF7+lgs7NMEd94AtRFbhfv8078l51mudTmmpPbgP45NKsvwnuIRPgMGLtBR4LAhmiteW4HEayc5J+kNqQ4zZZZ0busJJWTyRT8elmrCmzcAZh2n6WYn4Pv45fBlEZ1g35Mkd3JmWayuBTWvOmcTtjhVUeS+LT+Q4JqCZYrU7FHCdEoOlFCo+0MeL/FpOCiJNY0YfeLVkittqOEk3KtHl9AEtR0VFDHt8hba7W15fpcQX1EYO8wAX1rI+NWxLnB5sYHzWqLNan0eq5Y7YM8RZjLjWso3dj5RrY5mZklQGevxBGKBy08ih+TM3zul4G7Gn9wQwcbyGrnzYf5KxOMmNltg/Rcudr8e5cLDHaVB6XWqzJQIGKegveZGBmY2zm3s63jVAm//dyavC5AOMorobkklNljksdmoFzr6uv/ndc+miTRaOULMQF0AXRkjwwveKV5i2Qab6+oX906YK46kskS0uxKBQq2upXEJTgbkDiI79rooM7Pv5YSYky6WC2YXQ1CHP5X7w2Yex3ydM6Hz3Cy2oPDjDifdfuiMHeLdoq/a6fVTIPz9agwzMP+HKWBOUXXJqqqpyRbaddN2DktxPTtsu/qFT83N9ONOv8+5uG7cgFgybIXeGjoLcfM2tpG24OiFbbEt3ODxYTYgtmY7GN0s91ciZWfzaczcMNAk2ezUH+335D7MN3ot/QpT51pUlS8Z8rjZ6wJXjb7DjWhJdlTnHHRQfPUo659SFlAFIuREzHuoV/N/3M9Y718UAuxL3zwbKuHM0MwG6QYIKKy+rbChqcXWhl5/IhlBmkN920nWvlKLAwrRS67NuiRLb5CR4xZJ2DOPvqW1fuiLLk3H8N2IZ0oGFOKHI9WMjrIq8e/o9L6YFzEldys4CP2XeQHYIzEbJ0/XhzjoTVbsfZdIqfV9hZjUzybw3nhPRwITZfh5XSzpnqCvcfx8PNdNM8fcznq5u47JQ1u73jBRObfFoZlB7yt+o8vHoQ/pGKjN1M8yAMMIitsqVmKZW4Kn0rXLbwQa9eAi+0uUaARztTtnMT+YZq7e88VTkN/jhVPwtVHNTDGtfrjKOVvR3mjMerjUkOOPruVVTcrtH1Ccr/XADBEbxrXAxqSPpu0TosF0EXzNzSGPGPSMZNeE69kgl7rRnueSZZeGfAdnDFit/4WcJtCYtnuY8PSeWZUZf604gNeIoOF1KbOgkKHgi4DSZrRaba1GRWK58ouFQvMe8kkC+VZ8s7DDVVtIZKfUJqDLNwUPxJ01OHYbbZyksJRWQUWYL8Kt9kQsqYkjKH6c6eH6R5P7vZpX/dU0d/c/wPSsttuv9URXesKAHLzQtdG+3b1jQAv2i
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mqtt-server-certificate
      namespace: mqtt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mqtt-broker
  name: mqtt-broker
  namespace: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
        - image: eclipse-mosquitto:2.0
          name: eclipse-mosquitto
          ports:
            - containerPort: 8883
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mosquitto-cfg
              readOnly: true
            - mountPath: /etc/mosquitto/cert
              name: mqtt-server-certificate
              readOnly: true
      volumes:
        - name: mosquitto-cfg
          configMap:
            name: mosquitto-config
            items:
              - key: mosquitto.conf
                path: mosquitto.conf
        - name: mqtt-server-certificate
          secret:
            secretName: mqtt-server-certificate

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mqtt-broker
  name: mqtt-broker
  namespace: mqtt
spec:
  ports:
    - nodePort: 31883
      port: 8883
      protocol: TCP
      targetPort: 8883
  selector:
    app: mqtt-broker
  type: NodePort
status:
  loadBalancer: {}
