services:
  api_backend:
    container_name: api_backend
    build:
      context: .
      args:
        TZ: Asia/Tokyo
    depends_on:
      - db
    environment:
      DB_HOST: db:3306
      DB_USERNAME: mysqluser
      DB_PASSWORD: mypassword
      DB_NAME: touring
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      REGION: ${REGION}
      BUCKET: ${BUCKET}
      DATABASE: ${DATABASE}
      TABLE: ${TABLE}
      S3_OUTPUT_LOCATION: ${S3_OUTPUT_LOCATION}
    ports:
      - 8080:8080
    restart: always

  db:
    container_name: db
    image: mysql/mysql-server:8.0.29
    volumes:
      - db-store:/var/lib/mysql
      - ./db/tmp/log:/var/log/mysql
      - ./db/cnf/my.cnf:/etc/my.cnf
    environment:
      # allow access from hosts out of container
      # https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: touring
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: Asia/Tokyo
    ports:
      - 3306:3306

volumes:
  db-store:
