services:
  api_backend:
    container_name: api_backend
    build:
      context: .
      args:
        TZ: Asia/Tokyo
    depends_on:
      - db
    environment:
      DB_HOST: db:3306
      DB_USERNAME: mysqluser
      DB_PASSWORD: mypassword
      DB_NAME: touring
    ports:
      - 8080:8080
    restart: always

  db:
    container_name: db
    image: mysql/mysql-server:5.7
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      # allow access from hosts out of container
      # https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: touring
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
