name: Create and publish image

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build_and_push_vpn_client:
    uses: ./.github/workflows/build-workflow.yml
    with:
      targetDir: vpn-client
      tag: ${{ github.ref_name }}

  test_data_store:
    uses: ./.github/workflows/test-workflow.yml
    with:
      targetDir: data-store

  build_and_push_data_store:
    needs: test_data_store
    uses: ./.github/workflows/build-workflow.yml
    with:
      targetDir: data-store
      tag: ${{ github.ref_name }}

  build_and_upload_frontend:
    uses: ./.github/workflows/react-build-workflow.yml
    with:
      tag: ${{ github.ref_name }}
    secrets:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}

  test_api_backent:
    uses: ./.github/workflows/test-workflow.yml
    with:
      targetDir: api-backend

  build_and_push_api_backend:
    needs: test_api_backent
    uses: ./.github/workflows/build-workflow.yml
    with:
      targetDir: api-backend
      tag: ${{ github.ref_name }}
