name: Test

on:
  workflow_call:
    inputs:
      targetDir:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Test
        run: |
          cd ${{ inputs.targetDir }}
          go test -v ./...
        env:
          TZ: Asia/Tokyo
